#!/bin/sh
# usage: m1test <name> <initfile> [<initflags>] <queryargs>'
# test recording script
#
#  This file is
#    Copyright (C) 1998-2000 Ian Jackson <ian@davenant.greenend.org.uk>
#
#  It is part of adns, which is
#    Copyright (C) 1997-2000 Ian Jackson <ian@davenant.greenend.org.uk>
#    Copyright (C) 1999 Tony Finch <dot@dotat.at>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. 

set -e

if [ $# -lt 3 ]
then
	echo >&2 'usage: m1test <name> <initfile> [<initflags>] <queryargs>'
	exit 1
fi

case="case-$1"; shift
initfile="$1"; shift

case "$1" in
-*)	initflags="$1"; shift
esac

queryargs="$*"

initstring="`cat init-$initfile.text`"

echo $initfile $initflags >"$case.sys"
echo "$queryargs" >>"$case.sys"

EF_DISABLE_BANNER=1
export EF_DISABLE_BANNER

echo running hrecord $initflags "/... $queryargs"
set +e
ADNS_TEST_OUT_FD=3 3>>"$case.sys" >"$case.out" 2>"$case.err" </dev/null \
 ./hrecord $initflags "/$initstring" $queryargs
rc=$?
set -e

echo "rc=$rc" >>$case.out

egrep . -- "$case.err" "$case.out"
echo "exit status: $rc"
