#!/bin/sh
# usage: r1test <testcasename>

set -e
casename="$1"
case="case-$casename"
ocase="output-$casename"

exec <"$case.sys"
read initfile initflags
read queryargs

initstring="`cat init-$initfile.text`"

rm -f $ocase.*

set +e
ADNS_TEST_REPORT_FD=3 3>>"$ocase.report" >"$ocase.out" 2>"$ocase.err" \
 ./hplayback $initflags "/$initstring" $queryargs
rc=$?
set -e

echo "rc=$rc" >>$ocase.out

failed=false
for part in err out
do
	if diff -u -- "$case.$part" "$ocase.$part"
	then
		:
	else
		failed=true
	fi
done

if $failed
then
	echo >&2 "FAILED $case - WRONG OUTPUT - lines of syscall remaining `wc -l`"
	exit 2
fi

echo -n "$casename "

exit 0
